export const REQUEST_GET_LAUNCHES = 'REQUEST_GET_LAUNCHES';
export const SET_LAUNCHES = 'SET_LAUNCHES';
export const REQUEST_SET_FAVORITE = 'REQUEST_SET_FAVORITE';
export const SET_FAVORITE = 'SET_FAVORITE';